export enum UserProfile {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  PROMOTER = 'PROMOTER',
  STOREKEEPER = 'STOREKEEPER',
  SECRETARY = 'SECRETARY',
  GESTIONNAIRE = 'GESTIONNAIRE',
  RECOVERY_MANAGER = 'RECOVERY_MANAGER',
}
