site_name: Guide Utilisateur AMENOUVEVE-YAVEH
theme:
  name: material
  language: fr
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.expand
    - navigation.sections

nav:
  - Accueil: index.md
  - Guide Gestionnaire:
    - Introduction & Connexion: manager/index.md
    - Tableaux de Bord: manager/dashboard.md
    - Opérations Quotidiennes: manager/operations.md
    - Stocks & Ventes: manager/stock_sales.md
    - Finances & Tontines: manager/finance.md
    - Rapports & Configuration: manager/reporting_config.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
