-- Auto-inscription customer-space : statut d'activation client + dépôt initial déclaratif

ALTER TABLE public.client
    ADD COLUMN IF NOT EXISTS activation_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN IF NOT EXISTS activation_rejection_reason VARCHAR(500),
    ADD COLUMN IF NOT EXISTS activation_rejected_by VARCHAR(100),
    ADD COLUMN IF NOT EXISTS activation_rejected_at TIMESTAMP(6) WITHOUT TIME ZONE;

UPDATE public.client
SET activation_status = 'ACTIVE'
WHERE activation_status IS NULL OR activation_status = '';

ALTER TABLE public.client
    DROP CONSTRAINT IF EXISTS client_activation_status_check;

ALTER TABLE public.client
    ADD CONSTRAINT client_activation_status_check
        CHECK (activation_status IN ('PENDING', 'ACTIVE', 'REJECTED'));

CREATE INDEX IF NOT EXISTS idx_client_activation_status
    ON public.client (activation_status);

CREATE TABLE IF NOT EXISTS public.customer_initial_deposit_submission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reg_user_id VARCHAR(50) NOT NULL,
    date_reg TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    mod_user_id VARCHAR(50),
    date_mod TIMESTAMP(6) WITHOUT TIME ZONE,
    visibility VARCHAR(255) NOT NULL,
    client_id BIGINT NOT NULL,
    mobile_money_phone VARCHAR(20) NOT NULL,
    mobile_money_amount DOUBLE PRECISION NOT NULL,
    mobile_money_reference VARCHAR(100) NOT NULL,
    notes VARCHAR(255),
    status VARCHAR(20) NOT NULL,
    validated_by VARCHAR(100),
    validated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    rejected_by VARCHAR(100),
    rejected_at TIMESTAMP(6) WITHOUT TIME ZONE,
    rejection_reason VARCHAR(500),
    CONSTRAINT customer_initial_deposit_submission_status_check
        CHECK (status IN ('INITIE', 'VALIDE', 'REJETE')),
    CONSTRAINT customer_initial_deposit_submission_visibility_check
        CHECK (visibility IN ('ENABLED', 'DISABLED', 'DELETED'))
);

CREATE INDEX IF NOT EXISTS idx_cids_client
    ON public.customer_initial_deposit_submission (client_id);

CREATE INDEX IF NOT EXISTS idx_cids_status
    ON public.customer_initial_deposit_submission (status);

-- Au plus une soumission INITIE ou VALIDE par client
CREATE UNIQUE INDEX IF NOT EXISTS uk_cids_client_active
    ON public.customer_initial_deposit_submission (client_id)
    WHERE status IN ('INITIE', 'VALIDE') AND visibility <> 'DELETED';

-- Permission validation inscriptions
INSERT INTO uperm (reg_user_id, date_reg, visibility, permnam, permdfltnam)
SELECT 'System', NOW(), 'ENABLED', 'ROLE_VALIDATE_CLIENT_REGISTRATION', 'ROLE_VALIDATE_CLIENT_REGISTRATION'
WHERE NOT EXISTS (
    SELECT 1 FROM uperm WHERE permnam = 'ROLE_VALIDATE_CLIENT_REGISTRATION'
);

INSERT INTO upro_perms (permid, proid)
SELECT u.permid, pr.proid
FROM uperm u
CROSS JOIN upro pr
WHERE u.permnam = 'ROLE_VALIDATE_CLIENT_REGISTRATION'
  AND pr.name IN ('ADMIN', 'GESTIONNAIRE', 'MANAGER', 'RECOVERY_MANAGER')
  AND NOT EXISTS (
      SELECT 1 FROM upro_perms up
      WHERE up.permid = u.permid AND up.proid = pr.proid
  );

INSERT INTO uacc_perms (accid, permid)
SELECT a.accid, u.permid
FROM uacc a
JOIN upro pr ON pr.proid = a.proid
JOIN uperm u ON u.permnam = 'ROLE_VALIDATE_CLIENT_REGISTRATION'
WHERE pr.name IN ('ADMIN', 'GESTIONNAIRE', 'MANAGER', 'RECOVERY_MANAGER')
  AND NOT EXISTS (
      SELECT 1 FROM uacc_perms ap
      WHERE ap.accid = a.accid AND ap.permid = u.permid
  );
