-- Notifications destinées au client (espace client) — validations / refus BO

CREATE TABLE IF NOT EXISTS public.customer_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reg_user_id VARCHAR(50) NOT NULL,
    date_reg TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    mod_user_id VARCHAR(50),
    date_mod TIMESTAMP(6) WITHOUT TIME ZONE,
    visibility VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    client_id BIGINT NOT NULL,
    entity_id BIGINT,
    entity_reference VARCHAR(255),
    title VARCHAR(255) NOT NULL,
    message TEXT,
    amount DOUBLE PRECISION,
    operation_date DATE,
    link_path VARCHAR(512),
    link_query VARCHAR(1024),
    read_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT customer_notification_type_check
        CHECK (type IN (
            'REGISTRATION_ACTIVATED',
            'REGISTRATION_REJECTED',
            'CREDIT_PAYMENT_VALIDATED',
            'CREDIT_PAYMENT_REJECTED',
            'TONTINE_PAYMENT_VALIDATED',
            'TONTINE_PAYMENT_REJECTED',
            'ORDER_STATUS_CHANGED'
        )),
    CONSTRAINT customer_notification_visibility_check
        CHECK (visibility IN ('ENABLED', 'DISABLED', 'DELETED'))
);

CREATE INDEX IF NOT EXISTS idx_customer_notification_client_date
    ON public.customer_notification (client_id, date_reg DESC);

CREATE INDEX IF NOT EXISTS idx_customer_notification_client_unread
    ON public.customer_notification (client_id)
    WHERE read_at IS NULL AND visibility = 'ENABLED';

CREATE INDEX IF NOT EXISTS idx_customer_notification_type_entity
    ON public.customer_notification (type, entity_id);
