-- Source des commandes (personnel vs Espace Client) + lien demande de stock / commande.

ALTER TABLE public.orders
    ADD COLUMN IF NOT EXISTS source VARCHAR(30) NOT NULL DEFAULT 'STAFF';

ALTER TABLE public.orders
    DROP CONSTRAINT IF EXISTS orders_source_check;

ALTER TABLE public.orders
    ADD CONSTRAINT orders_source_check
    CHECK (source IN ('STAFF', 'CUSTOMER_SPACE'));

CREATE INDEX IF NOT EXISTS idx_orders_source ON public.orders (source);

-- Rattrapage : commandes créées par un compte Espace Client (customer_user_mapping).
UPDATE public.orders o
SET source = 'CUSTOMER_SPACE'
FROM public.customer_user_mapping m
WHERE m.client_id = o.client_id
  AND LOWER(m.username) = LOWER(o.reg_user_id)
  AND m.visibility <> 'DELETED'
  AND o.source = 'STAFF';

CREATE TABLE IF NOT EXISTS public.stock_request_order (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    stock_request_id bigint NOT NULL,
    order_id bigint NOT NULL,
    CONSTRAINT stock_request_order_pkey PRIMARY KEY (id),
    CONSTRAINT stock_request_order_visibility_check CHECK (
        (visibility)::text = ANY (ARRAY[
            ('ENABLED'::character varying)::text,
            ('DISABLED'::character varying)::text,
            ('DELETED'::character varying)::text
        ])
    ),
    CONSTRAINT fk_stock_request_order_request FOREIGN KEY (stock_request_id)
        REFERENCES public.stock_request (id),
    CONSTRAINT fk_stock_request_order_order FOREIGN KEY (order_id)
        REFERENCES public.orders (id)
);

ALTER TABLE public.stock_request_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_request_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE INDEX IF NOT EXISTS idx_stock_request_order_order_id
    ON public.stock_request_order (order_id);

CREATE INDEX IF NOT EXISTS idx_stock_request_order_request_id
    ON public.stock_request_order (stock_request_id);

CREATE UNIQUE INDEX IF NOT EXISTS uk_stock_request_order_active
    ON public.stock_request_order (stock_request_id, order_id)
    WHERE visibility <> 'DELETED';
