-- Justificatifs de paiement Mobile Money (capture / reçu PDF) + OCR Tesseract

CREATE TABLE IF NOT EXISTS public.customer_payment_proof (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    client_id bigint NOT NULL,
    bucket character varying(128) NOT NULL,
    object_key character varying(512) NOT NULL,
    content_type character varying(128) NOT NULL,
    original_file_name character varying(255),
    size_bytes bigint NOT NULL,
    sha256 character varying(64) NOT NULL,
    ocr_status character varying(30) NOT NULL,
    ocr_reference character varying(100),
    ocr_text text,
    linked_type character varying(30),
    linked_id bigint,
    linked_at timestamp(6) without time zone,
    CONSTRAINT customer_payment_proof_pkey PRIMARY KEY (id),
    CONSTRAINT customer_payment_proof_visibility_check CHECK (
        ((visibility)::text = ANY (ARRAY[
            ('ENABLED'::character varying)::text,
            ('DISABLED'::character varying)::text,
            ('DELETED'::character varying)::text
        ]))
    ),
    CONSTRAINT customer_payment_proof_ocr_status_check CHECK (
        ((ocr_status)::text = ANY (ARRAY[
            ('SUCCESS'::character varying)::text,
            ('NO_REFERENCE'::character varying)::text,
            ('FAILED'::character varying)::text,
            ('UNAVAILABLE'::character varying)::text
        ]))
    ),
    CONSTRAINT customer_payment_proof_linked_type_check CHECK (
        linked_type IS NULL OR ((linked_type)::text = ANY (ARRAY[
            ('CREDIT'::character varying)::text,
            ('TONTINE'::character varying)::text,
            ('INITIAL_DEPOSIT'::character varying)::text
        ]))
    )
);

ALTER TABLE public.customer_payment_proof ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_payment_proof_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE INDEX IF NOT EXISTS idx_customer_payment_proof_client_id
    ON public.customer_payment_proof (client_id);

CREATE INDEX IF NOT EXISTS idx_customer_payment_proof_sha256
    ON public.customer_payment_proof (sha256);

CREATE INDEX IF NOT EXISTS idx_customer_payment_proof_unlinked_date
    ON public.customer_payment_proof (date_reg)
    WHERE linked_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_customer_payment_proof_linked
    ON public.customer_payment_proof (linked_type, linked_id)
    WHERE linked_id IS NOT NULL;

ALTER TABLE public.customer_mobile_money_submission
    ADD COLUMN IF NOT EXISTS payment_proof_id bigint;

ALTER TABLE public.customer_tontine_mm_submission
    ADD COLUMN IF NOT EXISTS payment_proof_id bigint;

ALTER TABLE public.customer_initial_deposit_submission
    ADD COLUMN IF NOT EXISTS payment_proof_id bigint;

CREATE INDEX IF NOT EXISTS idx_customer_mm_submission_payment_proof
    ON public.customer_mobile_money_submission (payment_proof_id)
    WHERE payment_proof_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_customer_tontine_mm_submission_payment_proof
    ON public.customer_tontine_mm_submission (payment_proof_id)
    WHERE payment_proof_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_customer_initial_deposit_payment_proof
    ON public.customer_initial_deposit_submission (payment_proof_id)
    WHERE payment_proof_id IS NOT NULL;
