ALTER TABLE tontine_member ADD COLUMN IF NOT EXISTS frequency VARCHAR(255);
ALTER TABLE tontine_member ADD COLUMN IF NOT EXISTS amount DOUBLE PRECISION;
ALTER TABLE tontine_member ADD COLUMN IF NOT EXISTS notes TEXT;
