-- 1. Create Stock Tontine Request Tables
CREATE TABLE IF NOT EXISTS public.stock_tontine_request (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,

    reference character varying(255) UNIQUE,
    collector character varying(255),
    request_date date,
    validation_date date,
    delivery_date date,
    accounting_date date,
    total_sale_price double precision DEFAULT 0,
    total_purchase_price double precision DEFAULT 0,
    status character varying(255),

    CONSTRAINT stock_tontine_request_pkey PRIMARY KEY (id),
    CONSTRAINT stock_tontine_request_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public.stock_tontine_request_item (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,

    stock_tontine_request_id bigint,
    article_id bigint,
    quantity integer,
    unit_price double precision DEFAULT 0,
    purchase_price double precision DEFAULT 0,
    item_name character varying(255),

    CONSTRAINT stock_tontine_request_item_pkey PRIMARY KEY (id),
    CONSTRAINT stock_tontine_request_item_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[]))),
    CONSTRAINT fk_stock_tontine_request_item_request FOREIGN KEY (stock_tontine_request_id) REFERENCES public.stock_tontine_request(id),
    CONSTRAINT fk_stock_tontine_request_item_article FOREIGN KEY (article_id) REFERENCES public.articles(id)
);

-- 2. Create Stock Tontine Return Tables
CREATE TABLE IF NOT EXISTS public.stock_tontine_return (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,

    collector character varying(255),
    return_date date,
    status character varying(255),

    CONSTRAINT stock_tontine_return_pkey PRIMARY KEY (id),
    CONSTRAINT stock_tontine_return_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public.stock_tontine_return_item (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,

    stock_tontine_return_id bigint,
    article_id bigint,
    quantity integer,

    CONSTRAINT stock_tontine_return_item_pkey PRIMARY KEY (id),
    CONSTRAINT stock_tontine_return_item_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[]))),
    CONSTRAINT fk_stock_tontine_return_item_return FOREIGN KEY (stock_tontine_return_id) REFERENCES public.stock_tontine_return(id),
    CONSTRAINT fk_stock_tontine_return_item_article FOREIGN KEY (article_id) REFERENCES public.articles(id)
);

-- 3. Update Tontine Stock Table
ALTER TABLE public.tontine_stock
ADD COLUMN IF NOT EXISTS quantity_returned integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS weighted_average_unit_price double precision DEFAULT 0;

-- 4. Update Daily Commercial Report Table
ALTER TABLE public.daily_commercial_report
ADD COLUMN IF NOT EXISTS total_tontine_stock_request_amount double precision DEFAULT 0;

-- 5. Update Operation Type Check Constraint in Daily Operation Log
ALTER TABLE public.daily_operation_log DROP CONSTRAINT IF EXISTS daily_operation_log_type_check;

ALTER TABLE public.daily_operation_log
ADD CONSTRAINT daily_operation_log_type_check
CHECK (type IN (
    'CREDIT_COLLECTION',
    'TONTINE_COLLECTION',
    'ORDER',
    'NEW_ACCOUNT',
    'CASH_DEPOSIT',
    'STOCK_RETURN',
    'STOCK_REQUEST',
    'STOCK_TONTINE_REQUEST', -- New
    'STOCK_TONTINE_RETURN',  -- New
    'TONTINE_DELIVERY',
    'CREDIT_SALES',
    'NEW_CLIENT',
    'TONTINE_MEMBER_ENROLLMENT',
    'CREDIT',
    'TONTINE',
    'CASH'
));

-- Also update Credit table constraint just in case, to keep consistency with the Enum
ALTER TABLE public.credit DROP CONSTRAINT IF EXISTS credit_type_check;

ALTER TABLE public.credit
ADD CONSTRAINT credit_type_check
CHECK (type IN (
    'CREDIT_COLLECTION',
    'TONTINE_COLLECTION',
    'ORDER',
    'NEW_ACCOUNT',
    'CASH_DEPOSIT',
    'STOCK_RETURN',
    'STOCK_REQUEST',
    'STOCK_TONTINE_REQUEST', -- New
    'STOCK_TONTINE_RETURN',  -- New
    'TONTINE_DELIVERY',
    'CREDIT_SALES',
    'NEW_CLIENT',
    'TONTINE_MEMBER_ENROLLMENT',
    'CREDIT',
    'TONTINE',
    'CASH'
));
