CREATE TABLE IF NOT EXISTS public.tontine_stock_movement (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL DEFAULT 'ENABLED',
    tontine_stock_id bigint NOT NULL,
    credit_id bigint,
    credit_reference character varying(255),
    stock_tontine_request_id bigint,
    stock_tontine_request_reference character varying(255),
    stock_tontine_return_id bigint,
    collector character varying(255) NOT NULL,
    article_id bigint NOT NULL,
    article_name character varying(255),
    movement_type character varying(50) NOT NULL,
    quantity_before integer NOT NULL,
    quantity_moved integer NOT NULL,
    quantity_after integer NOT NULL,
    operation_date timestamp(6) without time zone NOT NULL,
    CONSTRAINT tontine_stock_movement_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);

CREATE INDEX IF NOT EXISTS idx_tontine_stock_movement_tontine_stock_id ON public.tontine_stock_movement (tontine_stock_id);
CREATE INDEX IF NOT EXISTS idx_tontine_stock_movement_credit_id ON public.tontine_stock_movement (credit_id);
CREATE INDEX IF NOT EXISTS idx_tontine_stock_movement_collector ON public.tontine_stock_movement (collector);
CREATE INDEX IF NOT EXISTS idx_tontine_stock_movement_request_id ON public.tontine_stock_movement (stock_tontine_request_id);
CREATE INDEX IF NOT EXISTS idx_tontine_stock_movement_return_id ON public.tontine_stock_movement (stock_tontine_return_id);
