-- Associate expenses with cash period remittances for net amount calculation
ALTER TABLE cash_period_remittance
    ADD COLUMN expense_amount double precision NOT NULL DEFAULT 0,
    ADD COLUMN net_amount double precision NOT NULL DEFAULT 0;

UPDATE cash_period_remittance SET net_amount = total_amount WHERE net_amount = 0;

CREATE TABLE IF NOT EXISTS cash_period_remittance_expense (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    remittance_id bigint NOT NULL,
    expense_id bigint NOT NULL,

    CONSTRAINT cash_period_remittance_expense_pkey PRIMARY KEY (id),
    CONSTRAINT cash_period_remittance_expense_remittance_fk FOREIGN KEY (remittance_id)
        REFERENCES cash_period_remittance(id) ON DELETE CASCADE,
    CONSTRAINT cash_period_remittance_expense_expense_fk FOREIGN KEY (expense_id)
        REFERENCES expense(id),
    CONSTRAINT cash_period_remittance_expense_unique UNIQUE (expense_id)
);

CREATE INDEX idx_cpr_expense_remittance_id ON cash_period_remittance_expense(remittance_id);
