-- Permissions KPI financiers par page.
-- Attribuées aux profils SUPER_ADMIN, ADMIN, GESTIONNAIRE, SECRETARY, PROMOTER
-- (jamais RECOVERY_MANAGER). Copiées aussi sur les comptes existants de ces profils.

INSERT INTO uperm (reg_user_id, date_reg, visibility, permnam, permdfltnam)
SELECT 'System', NOW(), 'ENABLED', p.permnam, p.permnam
FROM (VALUES
    ('ROLE_KPI_FINANCIER_VENTE'),
    ('ROLE_KPI_FINANCIER_RETARD'),
    ('ROLE_KPI_FINANCIER_ECHEANCE'),
    ('ROLE_KPI_FINANCIER_DASHBOARD'),
    ('ROLE_KPI_FINANCIER_RAPPORT_JOURNALIER'),
    ('ROLE_KPI_FINANCIER_TONTINE'),
    ('ROLE_KPI_FINANCIER_TONTINE_COLLECTE'),
    ('ROLE_KPI_FINANCIER_TONTINE_LIVRAISON'),
    ('ROLE_KPI_FINANCIER_TRANSFERT_VENTE'),
    ('ROLE_KPI_FINANCIER_BI_DASHBOARD'),
    ('ROLE_KPI_FINANCIER_BI_VENTES'),
    ('ROLE_KPI_FINANCIER_BI_RECOUVREMENT'),
    ('ROLE_KPI_FINANCIER_BI_STOCK'),
    ('ROLE_KPI_FINANCIER_DEPENSE')
) AS p(permnam)
WHERE NOT EXISTS (SELECT 1 FROM uperm WHERE permnam = p.permnam);

INSERT INTO upro_perms (permid, proid)
SELECT u.permid, pr.proid
FROM uperm u
CROSS JOIN upro pr
WHERE u.permnam IN (
    'ROLE_KPI_FINANCIER_VENTE',
    'ROLE_KPI_FINANCIER_RETARD',
    'ROLE_KPI_FINANCIER_ECHEANCE',
    'ROLE_KPI_FINANCIER_DASHBOARD',
    'ROLE_KPI_FINANCIER_RAPPORT_JOURNALIER',
    'ROLE_KPI_FINANCIER_TONTINE',
    'ROLE_KPI_FINANCIER_TONTINE_COLLECTE',
    'ROLE_KPI_FINANCIER_TONTINE_LIVRAISON',
    'ROLE_KPI_FINANCIER_TRANSFERT_VENTE',
    'ROLE_KPI_FINANCIER_BI_DASHBOARD',
    'ROLE_KPI_FINANCIER_BI_VENTES',
    'ROLE_KPI_FINANCIER_BI_RECOUVREMENT',
    'ROLE_KPI_FINANCIER_BI_STOCK',
    'ROLE_KPI_FINANCIER_DEPENSE'
)
  AND pr.name IN ('SUPER_ADMIN', 'ADMIN', 'GESTIONNAIRE', 'SECRETARY', 'PROMOTER')
  AND NOT EXISTS (
      SELECT 1 FROM upro_perms up
      WHERE up.permid = u.permid AND up.proid = pr.proid
  );

INSERT INTO uacc_perms (accid, permid)
SELECT a.accid, u.permid
FROM uacc a
JOIN upro pr ON pr.proid = a.proid
JOIN uperm u ON u.permnam IN (
    'ROLE_KPI_FINANCIER_VENTE',
    'ROLE_KPI_FINANCIER_RETARD',
    'ROLE_KPI_FINANCIER_ECHEANCE',
    'ROLE_KPI_FINANCIER_DASHBOARD',
    'ROLE_KPI_FINANCIER_RAPPORT_JOURNALIER',
    'ROLE_KPI_FINANCIER_TONTINE',
    'ROLE_KPI_FINANCIER_TONTINE_COLLECTE',
    'ROLE_KPI_FINANCIER_TONTINE_LIVRAISON',
    'ROLE_KPI_FINANCIER_TRANSFERT_VENTE',
    'ROLE_KPI_FINANCIER_BI_DASHBOARD',
    'ROLE_KPI_FINANCIER_BI_VENTES',
    'ROLE_KPI_FINANCIER_BI_RECOUVREMENT',
    'ROLE_KPI_FINANCIER_BI_STOCK',
    'ROLE_KPI_FINANCIER_DEPENSE'
)
WHERE pr.name IN ('SUPER_ADMIN', 'ADMIN', 'GESTIONNAIRE', 'SECRETARY', 'PROMOTER')
  AND NOT EXISTS (
      SELECT 1 FROM uacc_perms ap
      WHERE ap.accid = a.accid AND ap.permid = u.permid
  );
