CREATE TABLE IF NOT EXISTS article_type (
    id BIGSERIAL PRIMARY KEY,
    reg_user_id VARCHAR(50) NOT NULL,
    date_reg TIMESTAMP NOT NULL,
    mod_user_id VARCHAR(50),
    date_mod TIMESTAMP,
    visibility VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    code VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255)
);

INSERT INTO article_type (reg_user_id, date_reg, visibility, name, code, description)
VALUES 
('SYSTEM', CURRENT_TIMESTAMP, 'ENABLED', 'RIZ', 'RIZ', 'Catégorie RIZ'),
('SYSTEM', CURRENT_TIMESTAMP, 'ENABLED', 'HUILE', 'HUILE', 'Catégorie HUILE'),
('SYSTEM', CURRENT_TIMESTAMP, 'ENABLED', 'SPAGHETTI', 'SPAGHETTI', 'Catégorie SPAGHETTI'),
('SYSTEM', CURRENT_TIMESTAMP, 'ENABLED', 'SUCRE', 'SUCRE', 'Catégorie SUCRE'),
('SYSTEM', CURRENT_TIMESTAMP, 'ENABLED', 'COUSCOUS', 'COUSCOUS', 'Catégorie COUSCOUS'),
('SYSTEM', CURRENT_TIMESTAMP, 'ENABLED', 'CACAHOUETTE', 'CACAHOUETTE', 'Catégorie CACAHOUETTE'),
('SYSTEM', CURRENT_TIMESTAMP, 'ENABLED', 'SARDINE', 'SARDINE', 'Catégorie SARDINE'),
('SYSTEM', CURRENT_TIMESTAMP, 'ENABLED', 'CORN BOEUF', 'CORN_BOEUF', 'Catégorie CORN BOEUF'),
('SYSTEM', CURRENT_TIMESTAMP, 'ENABLED', 'MAYONNAISE', 'MAYONNAISE', 'Catégorie MAYONNAISE'),
('SYSTEM', CURRENT_TIMESTAMP, 'ENABLED', 'LIPTON', 'LIPTON', 'Catégorie LIPTON'),
('SYSTEM', CURRENT_TIMESTAMP, 'ENABLED', 'MAQUEREAU', 'MAQUEREAU', 'Catégorie MAQUEREAU'),
('SYSTEM', CURRENT_TIMESTAMP, 'ENABLED', 'LAIT', 'LAIT', 'Catégorie LAIT'),
('SYSTEM', CURRENT_TIMESTAMP, 'ENABLED', 'MILO', 'MILO', 'Catégorie MILO'),
('SYSTEM', CURRENT_TIMESTAMP, 'ENABLED', 'NESCAFE', 'NESCAFE', 'Catégorie NESCAFE'),
('SYSTEM', CURRENT_TIMESTAMP, 'ENABLED', 'TOMATE', 'TOMATE', 'Catégorie TOMATE'),
('SYSTEM', CURRENT_TIMESTAMP, 'ENABLED', 'CUBE', 'CUBE', 'Catégorie CUBE'),
('SYSTEM', CURRENT_TIMESTAMP, 'ENABLED', 'MAIS DOUX', 'MAIS_DOUX', 'Catégorie MAIS DOUX'),
('SYSTEM', CURRENT_TIMESTAMP, 'ENABLED', 'PETIT POIDS', 'PETIT_POIDS', 'Catégorie PETIT POIDS'),
('SYSTEM', CURRENT_TIMESTAMP, 'ENABLED', 'BEURRE', 'BEURRE', 'Catégorie BEURRE'),
('SYSTEM', CURRENT_TIMESTAMP, 'ENABLED', 'BOISSON', 'BOISSON', 'Catégorie BOISSON')
ON CONFLICT (name) DO NOTHING;
