ALTER TABLE stock_request
ADD COLUMN IF NOT EXISTS accounting_date DATE,
ADD COLUMN IF NOT EXISTS total_credit_sale_price DOUBLE PRECISION DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_purchase_price DOUBLE PRECISION DEFAULT 0;
