-- Refactor Credit type check to include all OperationType values
ALTER TABLE public.credit DROP CONSTRAINT IF EXISTS credit_type_check;

ALTER TABLE public.credit
ADD CONSTRAINT credit_type_check
CHECK (type IN (
    'CREDIT_COLLECTION',
    'TONTINE_COLLECTION',
    'ORDER',
    'NEW_ACCOUNT',
    'CASH_DEPOSIT',
    'STOCK_RETURN',
    'STOCK_REQUEST',
    'TONTINE_DELIVERY',
    'CREDIT_SALES',
    'NEW_CLIENT',
    'TONTINE_MEMBER_ENROLLMENT',
    'CREDIT',
    'TONTINE',
    'CASH'
));

-- Create Daily Commercial Report Table
CREATE TABLE IF NOT EXISTS public.daily_commercial_report (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    
    date date NOT NULL,
    commercial_username character varying(255) NOT NULL,
    
    total_stock_request_amount double precision DEFAULT 0,
    credit_sales_count integer DEFAULT 0,
    credit_sales_amount double precision DEFAULT 0,
    new_clients_count integer DEFAULT 0,
    new_accounts_balance double precision DEFAULT 0,
    collections_count integer DEFAULT 0,
    collections_amount double precision DEFAULT 0,
    orders_count integer DEFAULT 0,
    orders_amount double precision DEFAULT 0,
    tontine_members_count integer DEFAULT 0,
    tontine_collections_count integer DEFAULT 0,
    tontine_collections_amount double precision DEFAULT 0,
    tontine_deliveries_count integer DEFAULT 0,
    tontine_deliveries_amount double precision DEFAULT 0,
    total_amount_to_deposit double precision DEFAULT 0,
    total_amount_deposited double precision DEFAULT 0,
    
    CONSTRAINT daily_commercial_report_pkey PRIMARY KEY (id),
    CONSTRAINT daily_commercial_report_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);

-- Create Daily Operation Log Table
CREATE TABLE IF NOT EXISTS public.daily_operation_log (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    
    date date NOT NULL,
    commercial_username character varying(255) NOT NULL,
    timestamp timestamp(6) without time zone NOT NULL,
    type character varying(255) NOT NULL,
    amount double precision DEFAULT 0,
    reference character varying(255),
    description character varying(255),
    
    CONSTRAINT daily_operation_log_pkey PRIMARY KEY (id),
    CONSTRAINT daily_operation_log_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[]))),
    CONSTRAINT daily_operation_log_type_check CHECK (type IN (
        'CREDIT_COLLECTION',
        'TONTINE_COLLECTION',
        'ORDER',
        'NEW_ACCOUNT',
        'CASH_DEPOSIT',
        'STOCK_RETURN',
        'STOCK_REQUEST',
        'TONTINE_DELIVERY',
        'CREDIT_SALES',
        'NEW_CLIENT',
        'TONTINE_MEMBER_ENROLLMENT',
        'CREDIT',
        'TONTINE',
        'CASH'
    ))
);

-- Create Cash Deposit Table
CREATE TABLE IF NOT EXISTS public.cash_deposit (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    
    date date NOT NULL,
    commercial_username character varying(255) NOT NULL,
    amount double precision NOT NULL,
    billetage text,
    received_by character varying(255),
    daily_report_id bigint,
    
    CONSTRAINT cash_deposit_pkey PRIMARY KEY (id),
    CONSTRAINT cash_deposit_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[]))),
    CONSTRAINT fk_cash_deposit_daily_report FOREIGN KEY (daily_report_id) REFERENCES public.daily_commercial_report(id)
);
