CREATE TABLE IF NOT EXISTS public.article_price_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL DEFAULT 'ENABLED',
    article_id bigint NOT NULL,
    previous_purchase_price double precision NOT NULL,
    previous_selling_price double precision NOT NULL,
    previous_credit_sale_price double precision NOT NULL,
    new_purchase_price double precision NOT NULL,
    new_selling_price double precision NOT NULL,
    new_credit_sale_price double precision NOT NULL,
    CONSTRAINT article_price_history_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[]))),
    CONSTRAINT fk_article_price_history_article FOREIGN KEY (article_id) REFERENCES public.articles(id)
);

CREATE INDEX IF NOT EXISTS idx_article_price_history_article_id ON public.article_price_history (article_id);
