CREATE TABLE IF NOT EXISTS public.commercial_monthly_stock_item_sold_value_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL DEFAULT 'ENABLED',
    stock_item_id bigint NOT NULL,
    credit_id bigint,
    credit_reference character varying(255),
    movement_type character varying(50) NOT NULL,
    quantity integer NOT NULL,
    sale_unit_price double precision NOT NULL,
    weighted_average_unit_price double precision NOT NULL,
    previous_total_sold_value double precision NOT NULL,
    new_total_sold_value double precision NOT NULL,
    delta_value double precision NOT NULL,
    CONSTRAINT commercial_monthly_stock_item_sold_value_history_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[]))),
    CONSTRAINT fk_cmsi_sold_value_history_stock_item FOREIGN KEY (stock_item_id) REFERENCES public.commercial_monthly_stock_item(id)
);

CREATE INDEX IF NOT EXISTS idx_cmsi_sold_value_history_stock_item_id ON public.commercial_monthly_stock_item_sold_value_history (stock_item_id);
CREATE INDEX IF NOT EXISTS idx_cmsi_sold_value_history_credit_id ON public.commercial_monthly_stock_item_sold_value_history (credit_id);
