CREATE TABLE IF NOT EXISTS cash_period_remittance (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,

    year integer NOT NULL,
    month integer NOT NULL,
    total_amount double precision NOT NULL DEFAULT 0,
    credit_amount double precision NOT NULL DEFAULT 0,
    tontine_amount double precision NOT NULL DEFAULT 0,
    new_balance_amount double precision NOT NULL DEFAULT 0,
    status character varying(50) NOT NULL,
    initiated_by character varying(50) NOT NULL,
    submitted_by character varying(255),
    received_by character varying(255),
    submitted_at timestamp(6) without time zone,
    received_at timestamp(6) without time zone,
    reference character varying(255) NOT NULL,

    CONSTRAINT cash_period_remittance_pkey PRIMARY KEY (id),
    CONSTRAINT cash_period_remittance_reference_key UNIQUE (reference),
    CONSTRAINT cash_period_remittance_year_month_key UNIQUE (year, month),
    CONSTRAINT cash_period_remittance_status_check CHECK (status IN ('PENDING', 'RECEIVED')),
    CONSTRAINT cash_period_remittance_initiated_by_check CHECK (initiated_by IN ('SECRETARY', 'MANAGER'))
);
