--
-- PostgreSQL database dump
--

-- Dumped from database version 14.2
-- Dumped by pg_dump version 16.2

-- Started on 2024-09-23 21:12:13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 210 (class 1259 OID 125011)
-- Name: account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    account_balance double precision NOT NULL,
    account_number character varying(255),
    status character varying(255),
    client_id bigint,
    CONSTRAINT account_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'ACTIF'::character varying, 'CLOSING'::character varying, 'CLOSED'::character varying])::text[]))),
    CONSTRAINT account_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 209 (class 1259 OID 125010)
-- Name: account_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 125020)
-- Name: accountancy_report_view; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accountancy_report_view (
    id bigint NOT NULL,
    accounting_date date,
    balance_difference double precision,
    collector character varying(255),
    collector_firstname character varying(255),
    collector_lastname character varying(255),
    collector_phone character varying(255),
    date_reg timestamp(6) without time zone,
    daily_accounting_id bigint,
    real_balance double precision,
    status smallint,
    system_balance double precision,
    visibility smallint,
    CONSTRAINT accountancy_report_view_status_check CHECK (((status >= 0) AND (status <= 2))),
    CONSTRAINT accountancy_report_view_visibility_check CHECK (((visibility >= 0) AND (visibility <= 2)))
);


--
-- TOC entry 213 (class 1259 OID 125030)
-- Name: accounting_day; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounting_day (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    accounting_date date,
    status character varying(255),
    CONSTRAINT accounting_day_status_check CHECK (((status)::text = ANY ((ARRAY['OPENED'::character varying, 'CLOSED'::character varying, 'CURRENT'::character varying, 'OLD'::character varying])::text[]))),
    CONSTRAINT accounting_day_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 212 (class 1259 OID 125029)
-- Name: accounting_day_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounting_day ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounting_day_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 125040)
-- Name: agency; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agency (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    code character varying(255),
    name character varying(255),
    phone character varying(255),
    secretary_contact character varying(255),
    secretary_name character varying(255),
    superviser_contact character varying(255),
    superviser_name character varying(255),
    CONSTRAINT agency_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 217 (class 1259 OID 125049)
-- Name: agency_daily_report; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agency_daily_report (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    balance double precision,
    collection double precision,
    day character varying(255),
    recovery_date date,
    spending double precision,
    agency_id bigint,
    agency_weekly_report_id bigint,
    CONSTRAINT agency_daily_report_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 216 (class 1259 OID 125048)
-- Name: agency_daily_report_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agency_daily_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agency_daily_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 125039)
-- Name: agency_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 125058)
-- Name: agency_weekly_deposit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agency_weekly_deposit (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    balance double precision,
    deposit_status character varying(255),
    irregularity_amount double precision,
    total_amount double precision,
    agency_weekly_report_id bigint,
    CONSTRAINT agency_weekly_deposit_deposit_status_check CHECK (((deposit_status)::text = ANY ((ARRAY['SURPLUS'::character varying, 'MANQUE'::character varying, 'NORMAL'::character varying])::text[]))),
    CONSTRAINT agency_weekly_deposit_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 218 (class 1259 OID 125057)
-- Name: agency_weekly_deposit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agency_weekly_deposit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agency_weekly_deposit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 125068)
-- Name: agency_weekly_report; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agency_weekly_report (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    status character varying(255),
    total_amount double precision,
    total_collection double precision,
    total_spending double precision,
    week_from date,
    week_number integer,
    week_to date,
    agency_id bigint,
    CONSTRAINT agency_weekly_report_status_check CHECK (((status)::text = ANY ((ARRAY['CURRENT'::character varying, 'OLD'::character varying])::text[]))),
    CONSTRAINT agency_weekly_report_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 220 (class 1259 OID 125067)
-- Name: agency_weekly_report_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agency_weekly_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agency_weekly_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 125078)
-- Name: article_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.article_history (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    final_quantity integer,
    initial_quantity integer,
    operation_date date,
    operation_quantity integer,
    operation_type smallint,
    operation_user character varying(255),
    articles_id bigint,
    CONSTRAINT article_history_operation_type_check CHECK (((operation_type >= 0) AND (operation_type <= 1))),
    CONSTRAINT article_history_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 222 (class 1259 OID 125077)
-- Name: article_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.article_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.article_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 125088)
-- Name: articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.articles (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    credit_sale_price double precision NOT NULL,
    marque character varying(255) NOT NULL,
    model character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    purchase_price double precision NOT NULL,
    selling_price double precision NOT NULL,
    stock_quantity integer,
    type character varying(255) NOT NULL,
    CONSTRAINT articles_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 224 (class 1259 OID 125087)
-- Name: articles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 125097)
-- Name: client; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.client (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    iddoc bytea,
    address character varying(255),
    cardid character varying(255),
    card_type character varying(255),
    collector character varying(255),
    contact_person_address character varying(255),
    contact_person_name character varying(255),
    contact_person_phone character varying(255),
    credit_in_progress boolean,
    date_of_birth date,
    firstname character varying(255),
    lastname character varying(255),
    occupation character varying(255),
    phone character varying(255),
    quarter character varying(255),
    CONSTRAINT client_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 226 (class 1259 OID 125096)
-- Name: client_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 125106)
-- Name: credit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credit (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    begin_date date,
    collector character varying(255),
    daily_paid boolean DEFAULT false,
    daily_stake double precision,
    effective_end_date date,
    expected_end_date date,
    late_days_count integer,
    remaining_days_count integer,
    solvency_note character varying(255),
    status character varying(255),
    total_amount double precision,
    total_amount_paid double precision,
    total_amount_remaining double precision,
    type character varying(255),
    client_id bigint,
    CONSTRAINT credit_solvency_note_check CHECK (((solvency_note)::text = ANY ((ARRAY['ND'::character varying, 'EARLY'::character varying, 'TIME'::character varying, 'LATE'::character varying])::text[]))),
    CONSTRAINT credit_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'VALIDATED'::character varying, 'INPROGRESS'::character varying, 'DELIVERED'::character varying, 'ENDED'::character varying, 'SETTLED'::character varying])::text[]))),
    CONSTRAINT credit_type_check CHECK (((type)::text = ANY ((ARRAY['CREDIT'::character varying, 'TONTINE'::character varying])::text[]))),
    CONSTRAINT credit_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 231 (class 1259 OID 125119)
-- Name: credit_articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credit_articles (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    quantity integer,
    articles_id bigint,
    credit_id bigint,
    CONSTRAINT credit_articles_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 230 (class 1259 OID 125118)
-- Name: credit_articles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.credit_articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.credit_articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 125105)
-- Name: credit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.credit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.credit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 125126)
-- Name: credit_timeline; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credit_timeline (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    amount double precision,
    collector character varying(255),
    normal_stake boolean,
    remaining_days_count integer,
    total_amount_remaining double precision,
    credit_id bigint,
    daily_accountancy_id bigint,
    CONSTRAINT credit_timeline_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 232 (class 1259 OID 125125)
-- Name: credit_timeline_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.credit_timeline ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.credit_timeline_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 125135)
-- Name: daily_accountancy; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_accountancy (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    accounting_date date,
    balance_difference double precision,
    collector character varying(255),
    is_opened boolean DEFAULT true,
    real_balance double precision,
    status character varying(255),
    system_balance double precision,
    ticketing_json character varying(255),
    daily_accounting_id bigint,
    CONSTRAINT daily_accountancy_status_check CHECK (((status)::text = ANY ((ARRAY['MISSING'::character varying, 'SURPLUS'::character varying, 'COMPLIANT'::character varying])::text[]))),
    CONSTRAINT daily_accountancy_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 234 (class 1259 OID 125134)
-- Name: daily_accountancy_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.daily_accountancy ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.daily_accountancy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 125146)
-- Name: daily_accounting; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_accounting (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    accounting_date date,
    status character varying(255),
    total_amount double precision,
    CONSTRAINT daily_accounting_status_check CHECK (((status)::text = ANY ((ARRAY['OPENED'::character varying, 'CLOSED'::character varying, 'CURRENT'::character varying, 'OLD'::character varying])::text[]))),
    CONSTRAINT daily_accounting_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 238 (class 1259 OID 125155)
-- Name: daily_accounting_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_accounting_accounts (
    daily_accounting_id bigint NOT NULL,
    accounts_id bigint NOT NULL
);


--
-- TOC entry 236 (class 1259 OID 125145)
-- Name: daily_accounting_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.daily_accounting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.daily_accounting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 125161)
-- Name: deployment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.deployment (
    id bigint NOT NULL,
    activation_code character varying(255),
    issued_date date,
    renew_date date,
    society_name character varying(255)
);


--
-- TOC entry 239 (class 1259 OID 125160)
-- Name: deployment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.deployment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deployment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 125169)
-- Name: licence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.licence (
    id bigint NOT NULL,
    activation_code character varying(255),
    expiration_date date,
    renewable boolean NOT NULL,
    used boolean NOT NULL
);


--
-- TOC entry 241 (class 1259 OID 125168)
-- Name: licence_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.licence ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.licence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 125175)
-- Name: locality; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.locality (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    name character varying(255),
    CONSTRAINT locality_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 243 (class 1259 OID 125174)
-- Name: locality_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.locality ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.locality_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 125184)
-- Name: promoter; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.promoter (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    date_of_birth date,
    name character varying(255),
    phone_number character varying(255),
    serial_number character varying(255),
    CONSTRAINT promoter_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 245 (class 1259 OID 125183)
-- Name: promoter_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.promoter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.promoter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 125193)
-- Name: refreshtoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refreshtoken (
    id bigint NOT NULL,
    expiry_date timestamp(6) with time zone NOT NULL,
    token character varying(255) NOT NULL,
    user_id bigint
);


--
-- TOC entry 247 (class 1259 OID 125192)
-- Name: refreshtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refreshtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refreshtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 125199)
-- Name: tontine; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tontine (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    begin_date date,
    effective_end_date date,
    expected_end_date date,
    monthly_stake double precision,
    promoter character varying(255),
    remaining_month_count integer,
    status smallint,
    total_amount double precision,
    total_amount_paid double precision,
    total_amount_remaining double precision,
    client_id bigint,
    CONSTRAINT tontine_status_check CHECK (((status >= 0) AND (status <= 5))),
    CONSTRAINT tontine_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 249 (class 1259 OID 125198)
-- Name: tontine_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tontine ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tontine_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 125209)
-- Name: tontine_timeline; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tontine_timeline (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    amount double precision,
    default_stake boolean,
    promoter character varying(255),
    remaining_months_count integer,
    total_amount_remaining double precision,
    tontine_id bigint,
    CONSTRAINT tontine_timeline_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 251 (class 1259 OID 125208)
-- Name: tontine_timeline_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tontine_timeline ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tontine_timeline_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 125218)
-- Name: uacc; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.uacc (
    accid bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    activation_key character varying(20),
    active boolean,
    failed_connexion_attempt integer,
    accpass character varying(120) NOT NULL,
    password_update_key character varying(20),
    password_update_time timestamp(6) without time zone,
    accuser character varying(20) NOT NULL,
    proid bigint NOT NULL,
    CONSTRAINT uacc_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 253 (class 1259 OID 125217)
-- Name: uacc_accid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.uacc ALTER COLUMN accid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.uacc_accid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 125227)
-- Name: uacc_perms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.uacc_perms (
    uacc_perms_id bigint NOT NULL,
    accid bigint,
    permid bigint
);


--
-- TOC entry 255 (class 1259 OID 125226)
-- Name: uacc_perms_uacc_perms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.uacc_perms ALTER COLUMN uacc_perms_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.uacc_perms_uacc_perms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 258 (class 1259 OID 125233)
-- Name: uperm; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.uperm (
    permid bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    permdfltnam character varying(255),
    permnam character varying(255),
    CONSTRAINT uperm_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 257 (class 1259 OID 125232)
-- Name: uperm_permid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.uperm ALTER COLUMN permid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.uperm_permid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 260 (class 1259 OID 125242)
-- Name: upro; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.upro (
    proid bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    name character varying(255),
    CONSTRAINT upro_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 262 (class 1259 OID 125251)
-- Name: upro_perms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.upro_perms (
    upro_perms_id bigint NOT NULL,
    permid bigint,
    proid bigint
);


--
-- TOC entry 261 (class 1259 OID 125250)
-- Name: upro_perms_upro_perms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.upro_perms ALTER COLUMN upro_perms_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.upro_perms_upro_perms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 125241)
-- Name: upro_proid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.upro ALTER COLUMN proid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.upro_proid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 264 (class 1259 OID 125257)
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    useid bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    useeml character varying(50) NOT NULL,
    usefstnam character varying(20) NOT NULL,
    usegend character varying(10) NOT NULL,
    uselstnam character varying(20) NOT NULL,
    usephon character varying(15) NOT NULL,
    accid bigint,
    CONSTRAINT users_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 263 (class 1259 OID 125256)
-- Name: users_useid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN useid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_useid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Completed on 2024-09-23 21:12:14

--
-- PostgreSQL database dump complete
--

