--
-- PostgreSQL database dump
--

-- Dumped from database version 14.2
-- Dumped by pg_dump version 16.2

-- Started on 2024-09-23 21:05:16

-- SET statement_timeout = 0;
-- SET lock_timeout = 0;
-- SET idle_in_transaction_session_timeout = 0;
-- SET client_encoding = 'UTF8';
-- SET standard_conforming_strings = on;
-- SELECT pg_catalog.set_config('search_path', '', false);
-- SET check_function_bodies = false;
-- SET xmloption = content;
-- SET client_min_messages = warning;
-- SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 210 (class 1259 OID 125011)
-- Name: account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    account_balance double precision NOT NULL,
    account_number character varying(255),
    status character varying(255),
    client_id bigint,
    CONSTRAINT account_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'ACTIF'::character varying, 'CLOSING'::character varying, 'CLOSED'::character varying])::text[]))),
    CONSTRAINT account_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 209 (class 1259 OID 125010)
-- Name: account_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 125020)
-- Name: accountancy_report_view; Type: TABLE; Schema: public; Owner: -
--

CREATE OR REPLACE VIEW public.accountancy_report_view AS  SELECT da.id,
                                                                 da.date_reg,
                                                                 da.visibility,
                                                                 da.accounting_date,
                                                                 da.balance_difference,
                                                                 da.collector,
                                                                 da.real_balance,
                                                                 da.status,
                                                                 da.system_balance,
                                                                 da.daily_accounting_id,
                                                                 u.usefstnam AS collector_firstname,
                                                                 u.uselstnam AS collector_lastname,
                                                                 u.usephon AS collector_phone
                                                          FROM daily_accountancy da
                                                                   JOIN uacc ua ON da.collector::text = ua.accuser::text
                                                                   JOIN users u ON u.accid = ua.accid;


--
-- TOC entry 213 (class 1259 OID 125030)
-- Name: accounting_day; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounting_day (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    accounting_date date,
    status character varying(255),
    CONSTRAINT accounting_day_status_check CHECK (((status)::text = ANY ((ARRAY['OPENED'::character varying, 'CLOSED'::character varying, 'CURRENT'::character varying, 'OLD'::character varying])::text[]))),
    CONSTRAINT accounting_day_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 212 (class 1259 OID 125029)
-- Name: accounting_day_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounting_day ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounting_day_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 125040)
-- Name: agency; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agency (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    code character varying(255),
    name character varying(255),
    phone character varying(255),
    secretary_contact character varying(255),
    secretary_name character varying(255),
    superviser_contact character varying(255),
    superviser_name character varying(255),
    CONSTRAINT agency_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 217 (class 1259 OID 125049)
-- Name: agency_daily_report; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agency_daily_report (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    balance double precision,
    collection double precision,
    day character varying(255),
    recovery_date date,
    spending double precision,
    agency_id bigint,
    agency_weekly_report_id bigint,
    CONSTRAINT agency_daily_report_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 216 (class 1259 OID 125048)
-- Name: agency_daily_report_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agency_daily_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agency_daily_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 125039)
-- Name: agency_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 125058)
-- Name: agency_weekly_deposit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agency_weekly_deposit (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    balance double precision,
    deposit_status character varying(255),
    irregularity_amount double precision,
    total_amount double precision,
    agency_weekly_report_id bigint,
    CONSTRAINT agency_weekly_deposit_deposit_status_check CHECK (((deposit_status)::text = ANY ((ARRAY['SURPLUS'::character varying, 'MANQUE'::character varying, 'NORMAL'::character varying])::text[]))),
    CONSTRAINT agency_weekly_deposit_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 218 (class 1259 OID 125057)
-- Name: agency_weekly_deposit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agency_weekly_deposit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agency_weekly_deposit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 125068)
-- Name: agency_weekly_report; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agency_weekly_report (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    status character varying(255),
    total_amount double precision,
    total_collection double precision,
    total_spending double precision,
    week_from date,
    week_number integer,
    week_to date,
    agency_id bigint,
    CONSTRAINT agency_weekly_report_status_check CHECK (((status)::text = ANY ((ARRAY['CURRENT'::character varying, 'OLD'::character varying])::text[]))),
    CONSTRAINT agency_weekly_report_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 220 (class 1259 OID 125067)
-- Name: agency_weekly_report_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agency_weekly_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agency_weekly_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 125078)
-- Name: article_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.article_history (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    final_quantity integer,
    initial_quantity integer,
    operation_date date,
    operation_quantity integer,
    operation_type smallint,
    operation_user character varying(255),
    articles_id bigint,
    CONSTRAINT article_history_operation_type_check CHECK (((operation_type >= 0) AND (operation_type <= 1))),
    CONSTRAINT article_history_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 222 (class 1259 OID 125077)
-- Name: article_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.article_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.article_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 125088)
-- Name: articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.articles (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    credit_sale_price double precision NOT NULL,
    marque character varying(255) NOT NULL,
    model character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    purchase_price double precision NOT NULL,
    selling_price double precision NOT NULL,
    stock_quantity integer,
    type character varying(255) NOT NULL,
    CONSTRAINT articles_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 224 (class 1259 OID 125087)
-- Name: articles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 125097)
-- Name: client; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.client (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    iddoc bytea,
    address character varying(255),
    cardid character varying(255),
    card_type character varying(255),
    collector character varying(255),
    contact_person_address character varying(255),
    contact_person_name character varying(255),
    contact_person_phone character varying(255),
    credit_in_progress boolean,
    date_of_birth date,
    firstname character varying(255),
    lastname character varying(255),
    occupation character varying(255),
    phone character varying(255),
    quarter character varying(255),
    CONSTRAINT client_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 226 (class 1259 OID 125096)
-- Name: client_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 125106)
-- Name: credit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credit (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    begin_date date,
    collector character varying(255),
    daily_paid boolean DEFAULT false,
    daily_stake double precision,
    effective_end_date date,
    expected_end_date date,
    late_days_count integer,
    remaining_days_count integer,
    solvency_note character varying(255),
    status character varying(255),
    total_amount double precision,
    total_amount_paid double precision,
    total_amount_remaining double precision,
    type character varying(255),
    client_id bigint,
    CONSTRAINT credit_solvency_note_check CHECK (((solvency_note)::text = ANY ((ARRAY['ND'::character varying, 'EARLY'::character varying, 'TIME'::character varying, 'LATE'::character varying])::text[]))),
    CONSTRAINT credit_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'VALIDATED'::character varying, 'INPROGRESS'::character varying, 'DELIVERED'::character varying, 'ENDED'::character varying, 'SETTLED'::character varying])::text[]))),
    CONSTRAINT credit_type_check CHECK (((type)::text = ANY ((ARRAY['CREDIT'::character varying, 'TONTINE'::character varying])::text[]))),
    CONSTRAINT credit_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 231 (class 1259 OID 125119)
-- Name: credit_articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credit_articles (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    quantity integer,
    articles_id bigint,
    credit_id bigint,
    CONSTRAINT credit_articles_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 230 (class 1259 OID 125118)
-- Name: credit_articles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.credit_articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.credit_articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 125105)
-- Name: credit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.credit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.credit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 125126)
-- Name: credit_timeline; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credit_timeline (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    amount double precision,
    collector character varying(255),
    normal_stake boolean,
    remaining_days_count integer,
    total_amount_remaining double precision,
    credit_id bigint,
    daily_accountancy_id bigint,
    CONSTRAINT credit_timeline_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 232 (class 1259 OID 125125)
-- Name: credit_timeline_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.credit_timeline ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.credit_timeline_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 125135)
-- Name: daily_accountancy; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_accountancy (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    accounting_date date,
    balance_difference double precision,
    collector character varying(255),
    is_opened boolean DEFAULT true,
    real_balance double precision,
    status character varying(255),
    system_balance double precision,
    ticketing_json character varying(255),
    daily_accounting_id bigint,
    CONSTRAINT daily_accountancy_status_check CHECK (((status)::text = ANY ((ARRAY['MISSING'::character varying, 'SURPLUS'::character varying, 'COMPLIANT'::character varying])::text[]))),
    CONSTRAINT daily_accountancy_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 234 (class 1259 OID 125134)
-- Name: daily_accountancy_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.daily_accountancy ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.daily_accountancy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 125146)
-- Name: daily_accounting; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_accounting (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    accounting_date date,
    status character varying(255),
    total_amount double precision,
    CONSTRAINT daily_accounting_status_check CHECK (((status)::text = ANY ((ARRAY['OPENED'::character varying, 'CLOSED'::character varying, 'CURRENT'::character varying, 'OLD'::character varying])::text[]))),
    CONSTRAINT daily_accounting_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 238 (class 1259 OID 125155)
-- Name: daily_accounting_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_accounting_accounts (
    daily_accounting_id bigint NOT NULL,
    accounts_id bigint NOT NULL
);


--
-- TOC entry 236 (class 1259 OID 125145)
-- Name: daily_accounting_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.daily_accounting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.daily_accounting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 125161)
-- Name: deployment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.deployment (
    id bigint NOT NULL,
    activation_code character varying(255),
    issued_date date,
    renew_date date,
    society_name character varying(255)
);


--
-- TOC entry 239 (class 1259 OID 125160)
-- Name: deployment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.deployment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deployment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 125169)
-- Name: licence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.licence (
    id bigint NOT NULL,
    activation_code character varying(255),
    expiration_date date,
    renewable boolean NOT NULL,
    used boolean NOT NULL
);


--
-- TOC entry 241 (class 1259 OID 125168)
-- Name: licence_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.licence ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.licence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 125175)
-- Name: locality; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.locality (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    name character varying(255),
    CONSTRAINT locality_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 243 (class 1259 OID 125174)
-- Name: locality_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.locality ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.locality_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 125184)
-- Name: promoter; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.promoter (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    date_of_birth date,
    name character varying(255),
    phone_number character varying(255),
    serial_number character varying(255),
    CONSTRAINT promoter_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 245 (class 1259 OID 125183)
-- Name: promoter_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.promoter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.promoter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 125193)
-- Name: refreshtoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refreshtoken (
    id bigint NOT NULL,
    expiry_date timestamp(6) with time zone NOT NULL,
    token character varying(255) NOT NULL,
    user_id bigint
);


--
-- TOC entry 247 (class 1259 OID 125192)
-- Name: refreshtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refreshtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refreshtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 125199)
-- Name: tontine; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tontine (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    begin_date date,
    effective_end_date date,
    expected_end_date date,
    monthly_stake double precision,
    promoter character varying(255),
    remaining_month_count integer,
    status smallint,
    total_amount double precision,
    total_amount_paid double precision,
    total_amount_remaining double precision,
    client_id bigint,
    CONSTRAINT tontine_status_check CHECK (((status >= 0) AND (status <= 5))),
    CONSTRAINT tontine_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 249 (class 1259 OID 125198)
-- Name: tontine_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tontine ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tontine_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 125209)
-- Name: tontine_timeline; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tontine_timeline (
    id bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    amount double precision,
    default_stake boolean,
    promoter character varying(255),
    remaining_months_count integer,
    total_amount_remaining double precision,
    tontine_id bigint,
    CONSTRAINT tontine_timeline_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 251 (class 1259 OID 125208)
-- Name: tontine_timeline_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tontine_timeline ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tontine_timeline_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 125218)
-- Name: uacc; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.uacc (
    accid bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    activation_key character varying(20),
    active boolean,
    failed_connexion_attempt integer,
    accpass character varying(120) NOT NULL,
    password_update_key character varying(20),
    password_update_time timestamp(6) without time zone,
    accuser character varying(20) NOT NULL,
    proid bigint NOT NULL,
    CONSTRAINT uacc_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 253 (class 1259 OID 125217)
-- Name: uacc_accid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.uacc ALTER COLUMN accid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.uacc_accid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 125227)
-- Name: uacc_perms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.uacc_perms (
    uacc_perms_id bigint NOT NULL,
    accid bigint,
    permid bigint
);


--
-- TOC entry 255 (class 1259 OID 125226)
-- Name: uacc_perms_uacc_perms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.uacc_perms ALTER COLUMN uacc_perms_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.uacc_perms_uacc_perms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 258 (class 1259 OID 125233)
-- Name: uperm; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.uperm (
    permid bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    permdfltnam character varying(255),
    permnam character varying(255),
    CONSTRAINT uperm_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 257 (class 1259 OID 125232)
-- Name: uperm_permid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.uperm ALTER COLUMN permid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.uperm_permid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 260 (class 1259 OID 125242)
-- Name: upro; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.upro (
    proid bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    name character varying(255),
    CONSTRAINT upro_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 262 (class 1259 OID 125251)
-- Name: upro_perms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.upro_perms (
    upro_perms_id bigint NOT NULL,
    permid bigint,
    proid bigint
);


--
-- TOC entry 261 (class 1259 OID 125250)
-- Name: upro_perms_upro_perms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.upro_perms ALTER COLUMN upro_perms_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.upro_perms_upro_perms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 125241)
-- Name: upro_proid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.upro ALTER COLUMN proid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.upro_proid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 264 (class 1259 OID 125257)
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    useid bigint NOT NULL,
    reg_user_id character varying(50) NOT NULL,
    date_reg timestamp(6) without time zone NOT NULL,
    mod_user_id character varying(50),
    date_mod timestamp(6) without time zone,
    visibility character varying(255) NOT NULL,
    useeml character varying(50) NOT NULL,
    usefstnam character varying(20) NOT NULL,
    usegend character varying(10) NOT NULL,
    uselstnam character varying(20) NOT NULL,
    usephon character varying(15) NOT NULL,
    accid bigint,
    CONSTRAINT users_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['ENABLED'::character varying, 'DISABLED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- TOC entry 263 (class 1259 OID 125256)
-- Name: users_useid_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN useid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_useid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3340 (class 2606 OID 125019)
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- TOC entry 3344 (class 2606 OID 125028)
-- Name: accountancy_report_view accountancy_report_view_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accountancy_report_view
    ADD CONSTRAINT accountancy_report_view_pkey PRIMARY KEY (id);


--
-- TOC entry 3346 (class 2606 OID 125038)
-- Name: accounting_day accounting_day_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounting_day
    ADD CONSTRAINT accounting_day_pkey PRIMARY KEY (id);


--
-- TOC entry 3352 (class 2606 OID 125056)
-- Name: agency_daily_report agency_daily_report_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agency_daily_report
    ADD CONSTRAINT agency_daily_report_pkey PRIMARY KEY (id);


--
-- TOC entry 3350 (class 2606 OID 125047)
-- Name: agency agency_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agency
    ADD CONSTRAINT agency_pkey PRIMARY KEY (id);


--
-- TOC entry 3354 (class 2606 OID 125066)
-- Name: agency_weekly_deposit agency_weekly_deposit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agency_weekly_deposit
    ADD CONSTRAINT agency_weekly_deposit_pkey PRIMARY KEY (id);


--
-- TOC entry 3356 (class 2606 OID 125076)
-- Name: agency_weekly_report agency_weekly_report_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agency_weekly_report
    ADD CONSTRAINT agency_weekly_report_pkey PRIMARY KEY (id);


--
-- TOC entry 3358 (class 2606 OID 125086)
-- Name: article_history article_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_history
    ADD CONSTRAINT article_history_pkey PRIMARY KEY (id);


--
-- TOC entry 3360 (class 2606 OID 125095)
-- Name: articles articles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_pkey PRIMARY KEY (id);


--
-- TOC entry 3362 (class 2606 OID 125104)
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (id);


--
-- TOC entry 3366 (class 2606 OID 125124)
-- Name: credit_articles credit_articles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_articles
    ADD CONSTRAINT credit_articles_pkey PRIMARY KEY (id);


--
-- TOC entry 3364 (class 2606 OID 125117)
-- Name: credit credit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit
    ADD CONSTRAINT credit_pkey PRIMARY KEY (id);


--
-- TOC entry 3368 (class 2606 OID 125133)
-- Name: credit_timeline credit_timeline_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_timeline
    ADD CONSTRAINT credit_timeline_pkey PRIMARY KEY (id);


--
-- TOC entry 3370 (class 2606 OID 125144)
-- Name: daily_accountancy daily_accountancy_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_accountancy
    ADD CONSTRAINT daily_accountancy_pkey PRIMARY KEY (id);


--
-- TOC entry 3374 (class 2606 OID 125159)
-- Name: daily_accounting_accounts daily_accounting_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_accounting_accounts
    ADD CONSTRAINT daily_accounting_accounts_pkey PRIMARY KEY (daily_accounting_id, accounts_id);


--
-- TOC entry 3372 (class 2606 OID 125154)
-- Name: daily_accounting daily_accounting_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_accounting
    ADD CONSTRAINT daily_accounting_pkey PRIMARY KEY (id);


--
-- TOC entry 3378 (class 2606 OID 125167)
-- Name: deployment deployment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deployment
    ADD CONSTRAINT deployment_pkey PRIMARY KEY (id);


--
-- TOC entry 3380 (class 2606 OID 125173)
-- Name: licence licence_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.licence
    ADD CONSTRAINT licence_pkey PRIMARY KEY (id);


--
-- TOC entry 3382 (class 2606 OID 125182)
-- Name: locality locality_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.locality
    ADD CONSTRAINT locality_pkey PRIMARY KEY (id);


--
-- TOC entry 3384 (class 2606 OID 125191)
-- Name: promoter promoter_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.promoter
    ADD CONSTRAINT promoter_pkey PRIMARY KEY (id);


--
-- TOC entry 3386 (class 2606 OID 125197)
-- Name: refreshtoken refreshtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refreshtoken
    ADD CONSTRAINT refreshtoken_pkey PRIMARY KEY (id);


--
-- TOC entry 3392 (class 2606 OID 125207)
-- Name: tontine tontine_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tontine
    ADD CONSTRAINT tontine_pkey PRIMARY KEY (id);


--
-- TOC entry 3394 (class 2606 OID 125216)
-- Name: tontine_timeline tontine_timeline_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tontine_timeline
    ADD CONSTRAINT tontine_timeline_pkey PRIMARY KEY (id);


--
-- TOC entry 3398 (class 2606 OID 125231)
-- Name: uacc_perms uacc_perms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.uacc_perms
    ADD CONSTRAINT uacc_perms_pkey PRIMARY KEY (uacc_perms_id);


--
-- TOC entry 3396 (class 2606 OID 125225)
-- Name: uacc uacc_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.uacc
    ADD CONSTRAINT uacc_pkey PRIMARY KEY (accid);


--
-- TOC entry 3342 (class 2606 OID 125264)
-- Name: account uk27blqkeba8ylg8ondsf5j5fmm; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT uk27blqkeba8ylg8ondsf5j5fmm UNIQUE (client_id);


--
-- TOC entry 3400 (class 2606 OID 125274)
-- Name: uacc_perms uk3i6qhnuawq28sy28brapp25rp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.uacc_perms
    ADD CONSTRAINT uk3i6qhnuawq28sy28brapp25rp UNIQUE (accid, permid);


--
-- TOC entry 3388 (class 2606 OID 125272)
-- Name: refreshtoken uk81otwtvdhcw7y3ipoijtlb1g3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refreshtoken
    ADD CONSTRAINT uk81otwtvdhcw7y3ipoijtlb1g3 UNIQUE (user_id);


--
-- TOC entry 3410 (class 2606 OID 125278)
-- Name: users ukd2u3x6g1d6w4r7qgl0k8d2tak; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukd2u3x6g1d6w4r7qgl0k8d2tak UNIQUE (accid);


--
-- TOC entry 3376 (class 2606 OID 125268)
-- Name: daily_accounting_accounts ukddxyx9oyha6xc7m46balt9v7n; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_accounting_accounts
    ADD CONSTRAINT ukddxyx9oyha6xc7m46balt9v7n UNIQUE (accounts_id);


--
-- TOC entry 3348 (class 2606 OID 125266)
-- Name: accounting_day uke1epmsfvfc1th41cmco43ykp5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounting_day
    ADD CONSTRAINT uke1epmsfvfc1th41cmco43ykp5 UNIQUE (accounting_date);


--
-- TOC entry 3406 (class 2606 OID 125276)
-- Name: upro_perms ukgmbm5rybhkh51l0oxdoude4cb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.upro_perms
    ADD CONSTRAINT ukgmbm5rybhkh51l0oxdoude4cb UNIQUE (proid, permid);


--
-- TOC entry 3390 (class 2606 OID 125270)
-- Name: refreshtoken ukor156wbneyk8noo4jstv55ii3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refreshtoken
    ADD CONSTRAINT ukor156wbneyk8noo4jstv55ii3 UNIQUE (token);


--
-- TOC entry 3412 (class 2606 OID 125280)
-- Name: users ukr7tixxf1qa1hyb2jovcl7xhhc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr7tixxf1qa1hyb2jovcl7xhhc UNIQUE (useeml);


--
-- TOC entry 3402 (class 2606 OID 125240)
-- Name: uperm uperm_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.uperm
    ADD CONSTRAINT uperm_pkey PRIMARY KEY (permid);


--
-- TOC entry 3408 (class 2606 OID 125255)
-- Name: upro_perms upro_perms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.upro_perms
    ADD CONSTRAINT upro_perms_pkey PRIMARY KEY (upro_perms_id);


--
-- TOC entry 3404 (class 2606 OID 125249)
-- Name: upro upro_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.upro
    ADD CONSTRAINT upro_pkey PRIMARY KEY (proid);


--
-- TOC entry 3414 (class 2606 OID 125262)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (useid);


--
-- TOC entry 3433 (class 2606 OID 125371)
-- Name: uacc_perms fk2je12t5hs1d5vss6xvfr7xvgv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.uacc_perms
    ADD CONSTRAINT fk2je12t5hs1d5vss6xvfr7xvgv FOREIGN KEY (accid) REFERENCES public.uacc(accid);


--
-- TOC entry 3431 (class 2606 OID 125361)
-- Name: tontine_timeline fk6degeu38xtjgfv0720m15ym8g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tontine_timeline
    ADD CONSTRAINT fk6degeu38xtjgfv0720m15ym8g FOREIGN KEY (tontine_id) REFERENCES public.tontine(id);


--
-- TOC entry 3419 (class 2606 OID 125301)
-- Name: agency_weekly_report fk812ttnllk0bdbs2wcfpsa2hvr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agency_weekly_report
    ADD CONSTRAINT fk812ttnllk0bdbs2wcfpsa2hvr FOREIGN KEY (agency_id) REFERENCES public.agency(id);


--
-- TOC entry 3429 (class 2606 OID 125351)
-- Name: refreshtoken fka652xrdji49m4isx38pp4p80p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refreshtoken
    ADD CONSTRAINT fka652xrdji49m4isx38pp4p80p FOREIGN KEY (user_id) REFERENCES public.users(useid);


--
-- TOC entry 3420 (class 2606 OID 125306)
-- Name: article_history fkckyhejk1q5yb4jiebv9sqxvou; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_history
    ADD CONSTRAINT fkckyhejk1q5yb4jiebv9sqxvou FOREIGN KEY (articles_id) REFERENCES public.articles(id);


--
-- TOC entry 3416 (class 2606 OID 125291)
-- Name: agency_daily_report fkff9sc3ow6u8xt0g1fidqqtasr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agency_daily_report
    ADD CONSTRAINT fkff9sc3ow6u8xt0g1fidqqtasr FOREIGN KEY (agency_weekly_report_id) REFERENCES public.agency_weekly_report(id);


--
-- TOC entry 3422 (class 2606 OID 125321)
-- Name: credit_articles fkfgrixs9s3cuyxcn4plnb77gf1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_articles
    ADD CONSTRAINT fkfgrixs9s3cuyxcn4plnb77gf1 FOREIGN KEY (credit_id) REFERENCES public.credit(id);


--
-- TOC entry 3437 (class 2606 OID 125391)
-- Name: users fkgbm3q7tbclbpehpsph9cyfaw2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkgbm3q7tbclbpehpsph9cyfaw2 FOREIGN KEY (accid) REFERENCES public.uacc(accid);


--
-- TOC entry 3434 (class 2606 OID 125376)
-- Name: uacc_perms fki5ycd5f3xuoirgfjp6gkqa85j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.uacc_perms
    ADD CONSTRAINT fki5ycd5f3xuoirgfjp6gkqa85j FOREIGN KEY (permid) REFERENCES public.uperm(permid);


--
-- TOC entry 3430 (class 2606 OID 125356)
-- Name: tontine fkj5u05q64i0ntokhhtrveql7sd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tontine
    ADD CONSTRAINT fkj5u05q64i0ntokhhtrveql7sd FOREIGN KEY (client_id) REFERENCES public.client(id);


--
-- TOC entry 3426 (class 2606 OID 125336)
-- Name: daily_accountancy fkja03p4pluvc1x33anun16tsra; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_accountancy
    ADD CONSTRAINT fkja03p4pluvc1x33anun16tsra FOREIGN KEY (daily_accounting_id) REFERENCES public.daily_accounting(id);


--
-- TOC entry 3432 (class 2606 OID 125366)
-- Name: uacc fkjwd2j9bn6ggojvn22t9rvntgc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.uacc
    ADD CONSTRAINT fkjwd2j9bn6ggojvn22t9rvntgc FOREIGN KEY (proid) REFERENCES public.upro(proid);


--
-- TOC entry 3423 (class 2606 OID 125316)
-- Name: credit_articles fkk75abwgop790py0lvrtax8m1s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_articles
    ADD CONSTRAINT fkk75abwgop790py0lvrtax8m1s FOREIGN KEY (articles_id) REFERENCES public.articles(id);


--
-- TOC entry 3415 (class 2606 OID 125281)
-- Name: account fkkm8yb63h4ownvnlrbwnadntyn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT fkkm8yb63h4ownvnlrbwnadntyn FOREIGN KEY (client_id) REFERENCES public.client(id);


--
-- TOC entry 3424 (class 2606 OID 125326)
-- Name: credit_timeline fkl85x1gyws2ptw7jeten23it16; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_timeline
    ADD CONSTRAINT fkl85x1gyws2ptw7jeten23it16 FOREIGN KEY (credit_id) REFERENCES public.credit(id);


--
-- TOC entry 3417 (class 2606 OID 125286)
-- Name: agency_daily_report fklhjsjdxx4acnghgnmksipr3pr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agency_daily_report
    ADD CONSTRAINT fklhjsjdxx4acnghgnmksipr3pr FOREIGN KEY (agency_id) REFERENCES public.agency(id);


--
-- TOC entry 3435 (class 2606 OID 125386)
-- Name: upro_perms fklxk7xpogoalpaseqs77cqrgpd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.upro_perms
    ADD CONSTRAINT fklxk7xpogoalpaseqs77cqrgpd FOREIGN KEY (proid) REFERENCES public.upro(proid);


--
-- TOC entry 3436 (class 2606 OID 125381)
-- Name: upro_perms fknxd5rd6337sb9ywmb95gf27tq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.upro_perms
    ADD CONSTRAINT fknxd5rd6337sb9ywmb95gf27tq FOREIGN KEY (permid) REFERENCES public.uperm(permid);


--
-- TOC entry 3427 (class 2606 OID 125341)
-- Name: daily_accounting_accounts fkqadbagavdgo96cuv4c8v16or0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_accounting_accounts
    ADD CONSTRAINT fkqadbagavdgo96cuv4c8v16or0 FOREIGN KEY (accounts_id) REFERENCES public.daily_accountancy(id);


--
-- TOC entry 3418 (class 2606 OID 125296)
-- Name: agency_weekly_deposit fkqlyde0um6m85f6psopfg9t4xt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agency_weekly_deposit
    ADD CONSTRAINT fkqlyde0um6m85f6psopfg9t4xt FOREIGN KEY (agency_weekly_report_id) REFERENCES public.agency_weekly_report(id);


--
-- TOC entry 3428 (class 2606 OID 125346)
-- Name: daily_accounting_accounts fkrl92rknf1cfjyjbesb34byukm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_accounting_accounts
    ADD CONSTRAINT fkrl92rknf1cfjyjbesb34byukm FOREIGN KEY (daily_accounting_id) REFERENCES public.daily_accounting(id);


--
-- TOC entry 3425 (class 2606 OID 125331)
-- Name: credit_timeline fks9gkbt8nboynjq1ntg63gx33s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_timeline
    ADD CONSTRAINT fks9gkbt8nboynjq1ntg63gx33s FOREIGN KEY (daily_accountancy_id) REFERENCES public.daily_accountancy(id);


--
-- TOC entry 3421 (class 2606 OID 125311)
-- Name: credit fksppfvdwdkxqtusccsjrgjd08b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit
    ADD CONSTRAINT fksppfvdwdkxqtusccsjrgjd08b FOREIGN KEY (client_id) REFERENCES public.client(id);


-- Completed on 2024-09-23 21:05:16

--
-- PostgreSQL database dump complete
--

CREATE OR REPLACE FUNCTION get_days_between_dates(begin_date DATE, end_date DATE)
RETURNS INTEGER AS $$
BEGIN
    -- Si begin_date est NULL, retourner 0
    IF begin_date IS NULL THEN
        RETURN 0;
END IF;

    -- Si end_date est NULL, retourner 0
    IF end_date IS NULL THEN
        RETURN 0;
END IF;

    -- Si current_date est inférieur à end_date, calculer current_date - begin_date
    -- Sinon calculer end_date - begin_date
    IF CURRENT_DATE < end_date THEN
        RETURN CURRENT_DATE - begin_date;
ELSE
        RETURN end_date - begin_date;
END IF;
END;
$$ LANGUAGE plpgsql;

ALTER TABLE credit
ALTER COLUMN client_type TYPE VARCHAR(30);


CREATE OR REPLACE VIEW  accountancy_report_view AS SELECT da.id,
                                                          da.date_reg,
                                                          da.visibility,
                                                          da.accounting_date,
                                                          da.balance_difference,
                                                          da.collector,
                                                          da.real_balance,
                                                          da.status,
                                                          da.system_balance,
                                                          da.daily_accounting_id,
                                                          u.usefstnam AS collector_firstname,
                                                          u.uselstnam AS collector_lastname,
                                                          u.usephon AS collector_phone
                                                   FROM daily_accountancy da
                                                   JOIN uacc ua ON da.collector::text = ua.accuser::text
                                                   JOIN users u ON u.accid = ua.accid;


-- NEXT Migration

UPDATE CREDIT SET release_date = begin_date, accounting_date = begin_date WHERE status = 'INPROGRESS';

UPDATE CREDIT SET paid_amount = paid_amount + advance WHERE advance IS NOT NULL;

CREATE UNIQUE INDEX uc_client_unique_non_null
    ON Client (firstname, lastname, date_of_birth, phone, quarter, cardid, visibility)
    WHERE firstname IS NOT NULL
   AND lastname IS NOT NULL
   AND date_of_birth IS NOT NULL
   AND phone IS NOT NULL
   AND quarter IS NOT NULL
   AND cardid IS NOT NULL
   AND visibility IS NOT NULL;

CREATE UNIQUE INDEX uc_credit_unique_non_null
    ON Credit (client_id, type, status, visibility, collector, client_type)
WHERE client_id IS NOT NULL
AND type IS NOT NULL
AND status IS NOT NULL
AND visibility IS NOT NULL
AND collector IS NOT NULL
AND client_type IS NOT NULL AND client_type = 'CLIENT';

CREATE UNIQUE INDEX idx_client_phone_unique
    ON Client (phone)
    WHERE phone IS NOT NULL AND phone != '';

CREATE UNIQUE INDEX idx_client_cardid_unique
    ON Client (cardid)
    WHERE cardid IS NOT NULL AND cardid != '';

ALTER TABLE Credit DROP CONSTRAINT credit_status_check;

-- Index sur la colonne 'collector'
CREATE INDEX idx_client_collector ON client (collector);

CREATE INDEX idx_credit_collector ON credit (collector);

-- Index sur la colonne 'client_type'
CREATE INDEX idx_client_client_type ON client (client_type);

CREATE INDEX idx_credit_client_type ON credit (client_type);

-- Index sur la colonne 'collector'
CREATE INDEX idx_credit_status ON client (status);



    ----nouveau update
 UPDATE  credit cu SET total_purchase = (SELECT sum(ca.quantity * a.purchase_price) AS "prix d'achat"
 	FROM credit c JOIN credit_articles ca ON c.id=ca.credit_id JOIN articles a ON ca.articles_id=a.id WHERE c.id=cu.id
 ) WHERE visibility ='ENABLED' AND total_purchase = 0


 Update credit_articles ca set unit_price = (SELECT a.credit_sale_price FROM articles a WHERE a.id = ca.articles_id)